DB migration checks space and uses mv

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -272,8 +272,6 @@ check_disk_space() {
     exit 70
   fi
 
-# Literal match intended
-# shellcheck disable=SC2076
   if [[ "${__free_space}" -lt 52428800 ]]; then
     echo
     echo "You have less than 50 GiB of free disk space:"
@@ -329,17 +327,40 @@ upgrade_postgres() {
       return 0
   fi
 
+  __source_size="$(dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
+    alpine:3 du -s /var/lib/postgresql/data/)"
+
+  __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
+  __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
+
+  re='^[0-9]+$'
+  if ! [[ "${__free_space}" =~ $re ]] ; then
+    echo "Unable to determine free disk space. This is likely a bug."
+    echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
+    exit 70
+  fi
+
+  if [[ "${__free_space}" -lt $(( __source_size + 10485760 )) ]]; then
+    echo
+    echo "You don't have enough space free to migrate the database."
+    echo "It is $(( __source_size / 1024 / 1024 )) GiB in size and you need as much free again."
+    echo
+    df -h "${__docker_dir}"
+    echo
+    return
+  fi
+
   __migrated_vol="$(basename "$(pwd)")_erapg-data-pg${__target_pg}-migrated"
   __backup_vol="$(basename "$(pwd)")_erapg-data-pg${__source_pg}-backup"
 
-  echo "Stopping Era"
+  echo "Stopping ${__app_name}"
   docompose stop era-node && docompose rm -f era-node
   echo "Stopping PostgreSQL"
   docompose stop postgres && docompose rm -f postgres
 
   echo
   echo "Migrating database from PostgreSQL ${__source_pg} to PostgreSQL ${__target_pg}"
-  echo "If this step fails, the Era node database is likely corrupted."
+  echo "If this step fails, the ${__app_name} database is likely corrupted."
   echo
 
   dodocker pull "pats22/postgres-upgrade:${__source_pg}-to-${__target_pg}"
@@ -357,19 +378,17 @@ upgrade_postgres() {
     >> /var/lib/postgres/pg_hba.conf'
 
   echo
-  echo "Migration complete, copying data in erapg-data volume to backup"
+  echo "Migration complete, moving data in erapg-data volume to backup"
+  __during_migrate=1
   dodocker volume create "${__backup_vol}"
   dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
     -v "${__backup_vol}":"/var/lib/postgresql/${__source_pg}/data" \
-    alpine:3 cp -a /var/lib/postgresql/data/. "/var/lib/postgresql/${__source_pg}/data/"
+    alpine:3 mv /var/lib/postgresql/data/. "/var/lib/postgresql/${__source_pg}/data/"
 
-  __during_migrate=1
   echo "Moving migrated data to erapg-data volume"
   dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
-    alpine:3 rm -rf /var/lib/postgresql/data/*
-  dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
     -v "${__migrated_vol}":"/var/lib/postgresql/${__target_pg}/data" \
-    alpine:3 cp -a "/var/lib/postgresql/${__target_pg}/data/." /var/lib/postgresql/data/
+    alpine:3 mv "/var/lib/postgresql/${__target_pg}/data/." /var/lib/postgresql/data/
 
   __migrated=1
   dodocker volume remove "${__migrated_vol}"
