Improve PostgreSQL migration

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -304,88 +304,88 @@ nag_os_version() {
 
 
 upgrade_postgres() {
-    __target_pg=16
-    __during_postgres=1
+  __source_vol="$(basename "$(pwd)")_erapg-data"
+  if [ -z "$(dodocker volume ls -q -f "name=${__source_vol}")" ]; then
+    return 0
+  fi
 
-    __source_vol="$(basename "$(pwd)")_erapg-data"
-    if [ -z "$(dodocker volume ls -q -f "name=${__source_vol}")" ]; then
+  __target_pg=16
+  __during_postgres=1
+
+  __source_pg="$(dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
+    alpine:3 cat /var/lib/postgresql/data/PG_VERSION)"
+
+  if [ "${__source_pg}" -lt "${__target_pg}" ]; then
+    echo "Era is using PostgreSQL ${__source_pg}. The current version is PostgreSQL ${__target_pg}."
+    echo
+    while true; do
+      read -rp "Would you like to migrate to PostgreSQL ${__target_pg}? (Y/n) " yn
+      case $yn in
+        [Nn]o | [Nn]  ) echo "Keeping PostgreSQL at version ${__source_pg}"; return 0;;
+        * ) break;;
+      esac
+    done
+  else
       return 0
-    fi
+  fi
 
-    __source_pg="$(dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
-        alpine:3 cat /var/lib/postgresql/data/PG_VERSION)"
+  __migrated_vol="$(basename "$(pwd)")_erapg-data-pg${__target_pg}-migrated"
+  __backup_vol="$(basename "$(pwd)")_erapg-data-pg${__source_pg}-backup"
 
-    if [ "${__source_pg}" -lt "${__target_pg}" ]; then
-        echo "Era is using PostgreSQL ${__source_pg}. The current version is PostgreSQL ${__target_pg}."
-        echo
-        while true; do
-            read -rp "Would you like to migrate to PostgreSQL ${__target_pg}? (Y/n) " yn
-            case $yn in
-                [Nn]o | [Nn]  ) echo "Keeping PostgreSQL at version ${__source_pg}"; return 0;;
-                * ) break;;
-            esac
-        done
-    else
-        return 0
-    fi
+  echo "Stopping Era"
+  docompose stop era-node && docompose rm -f era-node
+  echo "Stopping PostgreSQL"
+  docompose stop postgres && docompose rm -f postgres
 
-    __migrated_vol="$(basename "$(pwd)")_erapg-data-pg${__target_pg}-migrated"
-    __backup_vol="$(basename "$(pwd)")_erapg-data-pg${__source_pg}-backup"
+  echo
+  echo "Migrating database from PostgreSQL ${__source_pg} to PostgreSQL ${__target_pg}"
+  echo "If this step fails, the Era node database is likely corrupted."
+  echo
 
-    echo "Stopping Era"
-    docompose stop era-node && docompose rm -f era-node
-    echo "Stopping PostgreSQL"
-    docompose stop postgres && docompose rm -f postgres
+  dodocker pull "pats22/postgres-upgrade:${__source_pg}-to-${__target_pg}"
+  dodocker volume create "${__migrated_vol}"
+  dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/${__source_pg}/data" \
+    -v "${__migrated_vol}":"/var/lib/postgresql/${__target_pg}/data" \
+    "pats22/postgres-upgrade:${__source_pg}-to-${__target_pg}"
+  # Adjust ownership. We use 70; postgres-upgrade creates it with 999
+  dodocker run --rm -v "${__migrated_vol}":"/var/lib/postgres" \
+    alpine:3 chown -R 70:70 /var/lib/postgres
+  # Conversion can leave us with a pg_hba.conf that does not allow connections
+  dodocker run --rm -v "${__migrated_vol}":"/var/lib/postgres" \
+    alpine:3 sh -c 'grep -qxE "host\s+all\s+all\s+all\s+scram-sha-256" /var/lib/postgres/pg_hba.conf \
+    || echo "host    all             all             all                     scram-sha-256" \
+    >> /var/lib/postgres/pg_hba.conf'
 
-    echo
-    echo "Migrating database from PostgreSQL ${__source_pg} to PostgreSQL ${__target_pg}"
-    echo "If this step fails, the Era node database is likely corrupted."
-    echo
+  echo
+  echo "Migration complete, copying data in erapg-data volume to backup"
+  dodocker volume create "${__backup_vol}"
+  dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
+    -v "${__backup_vol}":"/var/lib/postgresql/${__source_pg}/data" \
+    alpine:3 cp -a /var/lib/postgresql/data/. "/var/lib/postgresql/${__source_pg}/data/"
 
-    dodocker pull "pats22/postgres-upgrade:${__source_pg}-to-${__target_pg}"
-    dodocker volume create "${__migrated_vol}"
-    dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/${__source_pg}/data" \
-        -v "${__migrated_vol}":"/var/lib/postgresql/${__target_pg}/data" \
-        "pats22/postgres-upgrade:${__source_pg}-to-${__target_pg}"
-    # Adjust ownership. We use 70; postgres-upgrade creates it with 999
-    dodocker run --rm -v "${__migrated_vol}":"/var/lib/postgres" \
-        alpine:3 chown -R 70:70 /var/lib/postgres
-    # Conversion can leave us with a pg_hba.conf that does not allow connections
-    dodocker run --rm -v "${__migrated_vol}":"/var/lib/postgres" \
-        alpine:3 sh -c 'grep -qxE "host\s+all\s+all\s+all\s+scram-sha-256" /var/lib/postgres/pg_hba.conf \
-        || echo "host    all             all             all                     scram-sha-256" \
-        >> /var/lib/postgres/pg_hba.conf'
+  __during_migrate=1
+  echo "Moving migrated data to erapg-data volume"
+  dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
+    alpine:3 rm -rf /var/lib/postgresql/data/*
+  dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
+    -v "${__migrated_vol}":"/var/lib/postgresql/${__target_pg}/data" \
+    alpine:3 cp -a "/var/lib/postgresql/${__target_pg}/data/." /var/lib/postgresql/data/
 
-    echo
-    echo "Migration complete, copying data in erapg-data volume to backup"
-    dodocker volume create "${__backup_vol}"
-    dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
-        -v "${__backup_vol}":"/var/lib/postgresql/${__source_pg}/data" \
-        alpine:3 cp -a /var/lib/postgresql/data/. "/var/lib/postgresql/${__source_pg}/data/"
+  __migrated=1
+  dodocker volume remove "${__migrated_vol}"
 
-    __during_migrate=1
-    echo "Moving migrated data to erapg-data volume"
-    dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
-        alpine:3 rm -rf /var/lib/postgresql/data/*
-    dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
-        -v "${__migrated_vol}":"/var/lib/postgresql/${__target_pg}/data" \
-        alpine:3 cp -a "/var/lib/postgresql/${__target_pg}/data/." /var/lib/postgresql/data/
-
-    __migrated=1
-    dodocker volume remove "${__migrated_vol}"
-
-    echo
-    echo "Adjusting PostgreSQL Docker tag"
-    var="PG_DOCKER_TAG"
+  echo
+  echo "Adjusting PostgreSQL Docker tag"
+  var="PG_DOCKER_TAG"
 # This gets used, but shellcheck doesn't recognize that
 # shellcheck disable=SC2034
-    PG_DOCKER_TAG=${__target_pg}-bookworm
-    set_value_in_env
-    echo "${__app_name} has been stopped. You'll need to run \"$__me up\" to start it again."
-    echo
-    echo "A copy of your old Era database is in the Docker volume ${__backup_vol}."
-    echo "Confirm that everything works, and then delete it with \"docker volume rm ${__backup_vol}\"."
-    __during_postgres=0
+  PG_DOCKER_TAG=${__target_pg}-bookworm
+  set_value_in_env
+  echo "${__app_name} has been stopped. You'll need to run \"$__me up\" to start it again."
+  echo
+  echo "A copy of your old Era database is in the Docker volume ${__backup_vol}."
+  echo "Confirm that everything works, and then delete it with \"docker volume rm ${__backup_vol}\"."
+  __during_postgres=0
 }
 
 
