Fix DB size math

diff --git a/ethd b/ethd
--- a/ethd
+++ b/ethd
@@ -328,7 +328,14 @@ upgrade_postgres() {
   fi
 
   __source_size="$(dodocker run --rm -v "${__source_vol}":"/var/lib/postgresql/data" \
-    alpine:3 du -s /var/lib/postgresql/data/)"
+    alpine:3 du -s /var/lib/postgresql/data/ | awk '{print $1}')"
+
+  re='^[0-9]+$'
+  if ! [[ "${__source_size}" =~ $re ]] ; then
+    echo "Unable to determine database size. This is likely a bug."
+    echo "__source_size is ${__source_size}"
+    return 70
+  fi
 
   __docker_dir=$(dodocker system info --format '{{.DockerRootDir}}')
   __free_space=$(df -P "${__docker_dir}" | awk '/[0-9]%/{print $(NF-2)}')
@@ -337,7 +344,7 @@ upgrade_postgres() {
   if ! [[ "${__free_space}" =~ $re ]] ; then
     echo "Unable to determine free disk space. This is likely a bug."
     echo "df reports $(df -P "${__docker_dir}") and __free_space is ${__free_space}"
-    exit 70
+    return 70
   fi
 
   if [[ "${__free_space}" -lt $(( __source_size + 10485760 )) ]]; then
